name: Build, Test, and Push Docker Image to Docker Hub

on:
  release:
    types:
      - published

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build back Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dump.fun-back:latest ./back

    - name: Save back Docker image as artifact
      run: docker save ${{ secrets.DOCKER_USERNAME }}/dump.fun-back:latest -o back-image.tar

    - name: Upload back Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: back-docker-image
        path: back-image.tar

  build-front:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build front Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dump.fun-front:latest ./front

    - name: Save front Docker image as artifact
      run: docker save ${{ secrets.DOCKER_USERNAME }}/dump.fun-front:latest -o front-image.tar

    - name: Upload front Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: front-docker-image
        path: front-image.tar

  test-back:
    runs-on: ubuntu-latest
    needs: build-back

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download back Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: back-docker-image

    - name: Load back Docker image
      run: docker load -i back-image.tar

    - name: Start back Docker container
      run: docker run -d -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/dump.fun-back:latest

    - name: Install dependencies
      run: npm install --prefix back

    - name: Run tests with Vitest
      run: npm test --prefix back

  test-front:
    runs-on: ubuntu-latest
    needs: build-front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download front Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: front-docker-image

    - name: Load front Docker image
      run: docker load -i front-image.tar

    - name: Start front Docker container
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/dump.fun-front:latest

    - name: Wait for the container to be ready
      run: sleep 10

    - name: Test front-end with curl
      run: curl -f http://localhost
  
  push-back:
    runs-on: ubuntu-latest
    needs: test-back

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download back Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: back-docker-image

    - name: Load back Docker image
      run: docker load -i back-image.tar

    - name: Push back Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dump.fun-back:latest

  push-front:
    runs-on: ubuntu-latest
    needs: test-front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download front Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: front-docker-image

    - name: Load front Docker image
      run: docker load -i front-image.tar

    - name: Push front Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dump.fun-front:latest